### ISSUE TITLE
RaycastHit not supported?

### ISSUE THREAD

**Issue by AndrewCromar** [v0lt13/EditorAttributes#11]
Hello, I am getting this error:

![image](https://github.com/user-attachments/assets/3375df4e-a357-484a-a0fc-bd26de74be98)

With this code:

```
[SerializeField, VerticalGroup(drawInBox: true, nameof(reverse), nameof(isGrounded), nameof(groundCheckHit), nameof(steerAngle), nameof(downhill), nameof(requestGearChange), nameof(lastGearInput))]
private Void Debug;

[SerializeField, HideInInspector] private bool reverse;

[SerializeField, HideInInspector] private bool isGrounded;
[SerializeField, HideInInspector] private RaycastHit groundCheckHit;

[SerializeField, HideInInspector] private float steerAngle;

[SerializeField, HideInInspector] private bool downhill;

[SerializeField, HideInInspector] private bool requestGearChange;
[SerializeField, HideInInspector] private bool lastGearInput;
```

I'm assuming you have not yet added support for RaycastHit type of variable. Am I correct?

**Comment by v0lt13** [comment]
RaycastHit is a serialized struct, serialized struct and classes, arrays, lists and unity events are not supported in groups because they do not draw correctly. Though I don't think I have tested it with vertical group I will have to double check at some point and see how well it works.

**Comment by v0lt13** [comment]
Ok, I finally checked and RaycastHit is not serialized by unity, its just a normal struct and cannot be displayed in the inspector even outside groups, but there were indeed issues with serialized structs in groups and they should be fixed in the next update.

**Comment by AndrewCromar** [comment]
I see, I guess I just didn't notice that it didn't show in the inspector when it was not in the group.
