### ISSUE TITLE
Add attribute for Layer

### ISSUE THREAD

**Issue by Racines** [v0lt13/EditorAttributes#15]
Maybe I didn't found it in documentation, but It would be great to support Layer attribute
https://discussions.unity.com/t/type-for-layer-selection/91723/3

**Comment by TylerTemp** [comment]
```c#
public LayerMask myLayer;
```

should just do the trick

**Comment by Racines** [comment]
no LayerMask allow to select multiple layers

**Comment by v0lt13** [comment]
Thats the whole point of a LayerMask, to have a multi select dropdown, you want a single select?

**Comment by Racines** [comment]
yes, I want to select only one layer. My use case is to select the layer to set on a generated GameObject.

**Comment by v0lt13** [comment]
You can use the dropdown attribute and give it an array of all layers then you can select a single layer

**Comment by v0lt13** [comment]
Also this is not an issue its a feature request so I'm going to close this and you can continue the thread in the discussions->ideas tab
