### ISSUE TITLE
EditorValidation call all OnValidate() on all scenes, even the ones that are not exported in the build

### ISSUE THREAD

**Issue by Racines** [v0lt13/EditorAttributes#17]
EditorValidation call all OnValidate() on all scripts of all scenes, even the ones that are not exported in the build.
Using the plugin Feels of MoreMountains, it cause side effect at build like disabling the vertical sync. One of the demo include a script that change it in OnValidate()

**Comment by v0lt13** [comment]
There is no OnValidate call, all the editor validation system does it check all objects in all scenes that use the Required or Validate attributes, i dont see how it would turn VSync off unless you turn it off in a function called by the Validate attribute

**Comment by W3ktor** [comment]
It would be great to have the opportunity to turn off validation completely or only run on scenes in build or on selected scenes.

**Comment by Racines** [comment]
I confirm that doing EditorValidation > Validate Scenes will call all OnValidate of all scenes in the project.
Even if you don't call them yourself, I suppose that EditorSceneManager.OpenScene will do it automatically.
I can understand that when you build you need to check scenes that are included in build. But it probably should not do that on other scenes.
You can test it with this simple project : [TestAttributes.zip](https://github.com/user-attachments/files/17747126/TestAttributes.zip)
I added a script to a scene that is not included in the build. This script print in the console "OnValidate()" when it's OnValidate() method is called. When you build or apply EditorValidation > Validate Scenes. The message is logged.

The VSync turned off is a scenario that happen to me because we are using the plugin Feels of MoreMountains. It's not directly related to your plugin of course but since EditorValidation call every OnValidate() of all scenes it call a demo scene of the plugin that disable VSync in it's OnValidate().

**Comment by v0lt13** [comment]
Aha I understand now, alright in that case I will make it so it will only check scenes in build, maybe add something like a preprocessor directive to manually exclude OnValidate calls. But note that it will take a bit before I work on the new update since I'm dealing with some stuff IRL

**Comment by Racines** [comment]
Yeah no problem, as a hotfix I disabled the OnValidate that cause the issue.
