### ISSUE TITLE
compiler warnings regarding mismatch of overridden function declarations in UnityTypeConverter

### ISSUE THREAD

**Issue by PyrateAkananto** [v0lt13/EditorAttributes#20]
My Visual Studio Code warns me...
`Nullability of type of parameter 'existingValue' doesn't match overridden member (possibly because of nullability attributes). [EditorAttributes.Editor]`
`Nullability of type of parameter 'value' doesn't match overridden member (possibly because of nullability attributes). [EditorAttributes.Editor]`

...which means...
```
namespace EditorAttributes.Editor.Utility
{
	public class UnityTypeConverter : JsonConverter
	{
		public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
```
...does not exactly fit to...
```
namespace Newtonsoft.Json
{
  public abstract class JsonConverter
  {
    public abstract object? ReadJson(JsonReader reader, Type objectType, object? existingValue, JsonSerializer serializer);
```
...and...
```
		public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer) 
```
...does not exactly fit to...
```
    public abstract void WriteJson(JsonWriter writer, object? value, JsonSerializer serializer);
```
...because in `namespace Newtonsoft.Json` there is...
```
#nullable enable
```
...plus 3 more questions marks in function declarations. That statement and the three question marks are not in `UnityTypeConverter.cs` which causes the warnings.

**Explanation**

Usually when declaring `GameObject something;` then `something` can even be `null`. With "nullable aware context" enabled `something` _is not allowed_ to be `null` and the compiler tries to warn you if it could become `null`. If you actually want it to be able to be `null` you have to declare it as `GameObject? something;`.

For a single C# file "nullable aware context" and "[nullable variable annotations](https://learn.microsoft.com/en-us/dotnet/csharp/nullable-references#nullable-variable-annotations)" can enabled by writing `#nullable enable` somewhere the top of the file.

For a whole Unity project it can be enabled in Project Settings > Player > Other Settings > Script Compilation > Additional Compiler Arguments by inserting the string `-nullable+` into that text field.

**Fix**

To fix those two warnings you need to add `#nullable enable` and three question marks to the file `UnityTypeConverter.cs`. Here is a [diff of those changes](https://github.com/user-attachments/files/18097152/UnityTypeConverter.cs.2.5.0.diff.txt).

**P.S.**

EditorAttributes is a really helpful library which already made many tasks a lot simpler for me. In addition I really appreciate it coming with a very permissive public domain license and a solid documentation. 👍

**Comment by PyrateAkananto** [comment]
@v0lt13 I cannot confirm that this issue was fixed. In the commit history for 2.5.1 I cannot find any relevant changes and after upgrading to 2.5.1 Unity's compiler again tells me...
```
Assets\Plugins\EditorAttributes\Editor\Scripts\Utilities\UnityTypeConverter.cs(15,26): warning CS8765: Nullability of type of parameter 'existingValue' doesn't match overridden member (possibly because of nullability attributes).
Assets\Plugins\EditorAttributes\Editor\Scripts\Utilities\UnityTypeConverter.cs(15,26): warning CS8765: Nullability of type of parameter 'existingValue' doesn't match overridden member (possibly because of nullability attributes).
```

**Comment by v0lt13** [comment]
My dumbass accidentally undid the fix for this before pushing the changes, coding at 1am do be like that. It should be fixed now.

**Comment by PyrateAkananto** [comment]
Thank you. It is not in the 2.5.1 release files yet, despite being mentioned in its changelog.
