### ISSUE TITLE
Errors on import.

### ISSUE THREAD

**Issue by AndrewCromar** [v0lt13/EditorAttributes#9]
When I import the package I get alot (257) of errors coming from the package.

![image](https://github.com/v0lt13/EditorAttributes/assets/90068691/00d35e45-4e28-4e15-ad99-89a2055fdd4c)

**Comment by v0lt13** [comment]
that is weird, can you open the sources and show the error there?

**Comment by SaudBako** [comment]
V2.2.0
![Screenshot 2024-07-22 at 7 28 47 PM](https://github.com/user-attachments/assets/9707b765-2335-48b3-b0c4-9479abb9f22a)
<img width="912" alt="Screenshot 2024-07-22 at 7 29 34 PM" src="https://github.com/user-attachments/assets/b202f4f0-3d1d-47ec-a24b-403105cddc22">
<img width="1060" alt="Screenshot 2024-07-22 at 7 29 51 PM" src="https://github.com/user-attachments/assets/f2985ed1-0d54-4df6-96da-5d53e84d058d">

**Comment by v0lt13** [comment]
What version of unity are you using?

**Comment by v0lt13** [comment]
Yeah unity 2021 is not supported becuase UI toolkit is not supported well on that version, if you want to use this package on 2021 try an older version of the package by going to the github releases. v2.1.1 is the newest version of the package that still uses ImGUI that one should still work on 2021

**Comment by AndrewCromar** [comment]
Hello @v0lt13, sorry it took me so long to reply, I was on vacation. The project I was using it in was using unity 2020.3.47f1 which biased on what you said I assume is not supported.

After testing in Unity 2022.2.13f1 the errors are gone and I was able to get it working.
